query MyQuery ($id: ID!){
  menu(id: $id, idType: NAME) {
    count
    id
    name
    menuItems {
      nodes {
        id
        url
        cssClasses
        label
        menu {
          menuIcon
        }
      }
    }
  }
}
