{
  projects {
    nodes {
      id
      link
      slug
      title
      uri
      date
      featuredImage {
        node {
          id
          srcSet(size: MEDIUM_LARGE)
        }
      }
    }
  }
}
