{
  projects(where: {tagNotIn: 86}) {
    nodes {
      id
      link
      slug
      excerpt
      title
      uri
      date
      projectExtra {
        projectPages
        projectFrameworkVersion
        projectLicence
        projectGithubRepoName
        projectLiveLink
        projectVideoLink
      }
      technologies {
        nodes {
          id
          name
          slug
          customFields {
            technologyColorCode
            technologyIcon
          }
        }
      }
      features {
        nodes {
          id
          name
          slug
        }
      }
      categories {
        nodes {
          id
          name
          slug
        }
      }
      tags {
        nodes {
          id
          name
          slug
        }
      }
      projectTypes(where: {slug: ["clones", "templates", "themes", "ui-components"]}) {
        nodes {
          id
          name
          slug
        }
      }
      featuredImage {
        node {
          id
          srcSet(size: MEDIUM)
          sourceUrl
        }
      }
    }
  }
}
